fix test
Signed-off-by: drivebyer <yang.wu@daocloud.io>

diff --git a/tests/e2e-chainsaw/v1beta2/ha-failover/chainsaw-test.yaml b/tests/e2e-chainsaw/v1beta2/ha-failover/chainsaw-test.yaml
--- a/tests/e2e-chainsaw/v1beta2/ha-failover/chainsaw-test.yaml
+++ b/tests/e2e-chainsaw/v1beta2/ha-failover/chainsaw-test.yaml
@@ -30,9 +30,13 @@ spec:
         - script:
             timeout: 10s
             content: |
-              MASTER_IP_FROM_SENTINEL=$(kubectl exec --namespace ${NAMESPACE} redis-sentinel-sentinel-0 -- redis-cli -p 26379 sentinel get-master-addr-by-name myMaster | head -n 1);
-              MASTER_IP_FROM_LABEL=$(kubectl -n ${NAMESPACE} get pod -l app=redis-replication,redis-role=master,redis_setup_type=replication -o jsonpath='{.items[0].status.podIP}');
-              if [ "${MASTER_IP_FROM_SENTINEL}" == "${MASTER_IP_FROM_LABEL}" ]; then echo "OK"; else echo "FAIL"; fi
+              #!/bin/bash
+              set -eu
+              ####
+              export MASTER_IP_FROM_SENTINEL=$(kubectl exec --namespace ${NAMESPACE} redis-sentinel-sentinel-0 -- redis-cli -p 26379 sentinel get-master-addr-by-name myMaster | head -n 1)
+              export MASTER_IP_FROM_LABEL=$(kubectl -n ${NAMESPACE} get pod -l app=redis-replication,redis-role=master,redis_setup_type=replication -o jsonpath='{.items[0].status.podIP}')
+              ####
+              if [ "$MASTER_IP_FROM_SENTINEL" == "$MASTER_IP_FROM_LABEL" ]; then echo "OK"; else echo "FAIL"; fi
             check:
               ($stdout=='OK'): true
       catch:
@@ -68,9 +72,13 @@ spec:
         - script:
             timeout: 10s
             content: |
-              MASTER_IP_FROM_SENTINEL=$(kubectl exec --namespace ${NAMESPACE} redis-sentinel-sentinel-0 -- redis-cli -p 26379 sentinel get-master-addr-by-name myMaster | head -n 1);
-              MASTER_IP_FROM_LABEL=$(kubectl -n ${NAMESPACE} get pod -l app=redis-replication,redis-role=master,redis_setup_type=replication -o jsonpath='{.items[0].status.podIP}');
-              if [ "${MASTER_IP_FROM_SENTINEL}" == "${MASTER_IP_FROM_LABEL}" ]; then echo "OK"; else echo "FAIL"; fi
+              #!/bin/bash
+              set -eu
+              ####
+              export MASTER_IP_FROM_SENTINEL=$(kubectl exec --namespace ${NAMESPACE} redis-sentinel-sentinel-0 -- redis-cli -p 26379 sentinel get-master-addr-by-name myMaster | head -n 1)
+              export MASTER_IP_FROM_LABEL=$(kubectl -n ${NAMESPACE} get pod -l app=redis-replication,redis-role=master,redis_setup_type=replication -o jsonpath='{.items[0].status.podIP}')
+              ####
+              if [ "$MASTER_IP_FROM_SENTINEL" == "$MASTER_IP_FROM_LABEL" ]; then echo "OK"; else echo "FAIL"; fi
             check:
               ($stdout=='OK'): true
       catch:
